session_id: 54321
data_shots_train_str: 'train'
data_shots_test_str: 'test'
 
model_name_lr: "logistic_regression_model" 
model_name_dt: "decision_tree_model" 
plot_output_path_lr: "data/08_reporting/shot_predictions_lr.png"
plot_output_path_dt: "data/08_reporting/shot_predictions_dt.png"